### ISSUE TITLE
dependabotの導入

### ISSUE THREAD

**Issue by Katsuyuki-Karasawa** [aipictors/aipictors#78]
```yml
version: 2
updates:
    - package-ecosystem: "npm"
    directory: "/"
    schedule:
        interval: "daily"
    target:
        branches:
            - "main"
    labels:
        - "Dependabot"
```

Renovateでもよさそう
